version: "3.9"

services:
  app:
    build: .
    container_name: vendor-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./app/database:/app/app/database
    environment:
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6380:6379"

